name: Trigger CI/CD

on:
  push:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger CI/CD repository
        env:
          GH_TOKEN: ${{ secrets.CICD_TRIGGER_TOKEN }}
        run: |
          gh api \
            --method POST \
            /repos/AyoubRhatous/petclinic-cicd/dispatches \
            -f event_type=app-commit \
            -f client_payload[sha]="${{ github.sha }}" \
            -f client_payload[branch]="${{ github.ref_name }}" \
            -f client_payload[repository]="${{ github.repository }}"
